### ISSUE TITLE
container doesn't start

### ISSUE THREAD

**Issue by soichih** [faskowit/app-fmri-2-mat#1]
I am testing this app on GCP with singularity 3.2.1-1.el7 (CentOS 7.6.1810). The App fails to start with the following error message..

```
WARNING: docker-extract failed, missing executable or libarchive
WARNING: Will use old layer extraction method - this does not handle whiteouts
[33mWARNING: Non existent bind point (file) in container: '/etc/localtime'
[0mFATAL: kernel too old
```

I've noticed that the singularity is invoked with --writable flag.

```
time singularity exec --writable -e docker://faskowit/app-fmri-2-mat \
	bash -c "./run.sh $@ "
```

I am not sure if --writable has to do with the error I am getting, but is it necessary?

**Comment by faskowit** [comment]
The writeable flag is just a legacy copy-pasta from some other code... you'd know better than me... but I don't think it's necessary.

**Comment by soichih** [comment]
Fixed by  https://github.com/faskowit/app-fmri-2-mat/pull/2
