### ISSUE TITLE
Smoothing 

### ISSUE THREAD

**Issue by dcoynel** [faskowit/app-fmri-2-mat#15]
Hi, do I understand correctly from src/regress.py that you use a default smoothing kernel of smoothkern=6mm?

Could this be added to the README, or given an option to change?

Thanks!

**Comment by faskowit** [comment]
Hi, Thanks for the feedback. Indeed 6mm is the default smoothing kernel.  If you are using the `run.sh` script, alternative options can be passed in via the `-regressextra` flag.  So it would look like this.

```run.sh -fmri .... -mask.... -regressextra -fwhm 3```

I'll add some of this in the readme.  I hope you find the code useful! 

Cheers!
