### ISSUE TITLE
Discrepancy between labels number and connmat shape error

### ISSUE THREAD

**Issue by Vince-LD** [faskowit/app-fmri-2-mat#17]
Hello!

I've been planning to use this app with my fmriprep outputs and [multiAtlas Transfer Tool](https://github.com/faskowit/multiAtlasTT) parcellations. It works flawlessly with the AAL atlas but always outputs an error when trying with aicha. 

```
Resampling labels
[NiftiLabelsMasker.transform_single_imgs] Loading data from Nifti1Image('aicha/output_regress/out_nuisance.nii.gz')
[NiftiLabelsMasker.transform_single_imgs] Extracting region signals
[NiftiLabelsMasker.transform_single_imgs] Cleaning extracted signals
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py", line 1675, in create_block_manager_from_blocks
    make_block(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/blocks.py", line 2742, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/blocks.py", line 142, in __init__
    raise ValueError(
ValueError: Wrong number of items passed 343, placement implies 345

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vincent/app-fmri-2-mat//src/makemat.py", line 156, in <module>
    main()
  File "/home/vincent/app-fmri-2-mat//src/makemat.py", line 123, in main
    conndf, connmat, times, regions = extract_mat(inputimg, inputmask, labimg,
  File "/home/vincent/app-fmri-2-mat//src/makemat.py", line 66, in extract_mat
    conndf = get_con_df(connmat, reglabs)
  File "/home/vincent/app-fmri-2-mat//src/makemat.py", line 37, in get_con_df
    con_df = pd.DataFrame(raw_mat, index=roi_names, columns=roi_names)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 558, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py", line 238, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py", line 1687, in create_block_manager_from_blocks
    raise construction_error(tot_items, blocks[0].shape[1:], axes, e)
ValueError: Shape of passed values is (343, 343), indices imply (345, 345)
output csv file not created! error
```

I have several hypothesis but I'm completely new to these tools (this app and nilearn in general) so I don't know how i can test 
and solve the issues.

First, i know the RoI 103 is missing from the parcellation but still exists in my LUT file. Accounting for that, i'm still missing 2 regions in the conmat. I did not find any way to handle a reference file to the app with all RoIs that should be present in the parcellation. Also, I have no way of knowing which regions are missing in nilearn outputs... My best bet is that because AICHA has a lot of RoIs, some may be so small that they disappear during the resampling. However I can't switch to `labels` resampling because I don't have enough RAM so I can't tell if it will solve my problems. 

Any idea of the origins of my problems and how i could solve them?

**Comment by faskowit** [comment]
hi!

Thanks for the interesting in the app.  Ya, this problem happens where there is a region in the atlas that does not have any signal 'underneath' it, so it causes a mix-up between the number of ROIs in the atlas, and the number of ROIs that should be parcellated by the nilearn function. Over the next few days, I'll look at ways to make it not error out, and instead output a row of "0"s or something for these missing regions. 

In the meantime, if you need results really quick, I would suggest using an atlas with fewer ROIs. Otherwise, I should have a little fix out within the week or so.

cheers, 
josh

**Comment by Vince-LD** [comment]
Thank you for you quick response! 

It would be great to add the feature you are proposing. Maybe giving a reference file with all the atlas RoIs would be an "easy" fix compared to making everything automated. Also, It would allow for an easy way to know how many RoIs there are. As stated in my post, the RoI 103 wasn't parcellated and it creates a gap in the `reginparc` variable in `makemat.py` that then may cause problem with pandas `DataFrame` creation. However, I cannot just reindex all parcellated regions because it will mess up my downstream analysis. Using a reference list would avoid such problem. I don't know in which measure it's possible to integrate such solution because of `nilearn`.

The app worked really well with my MaTT AAL output (82 RoIs), I'm gonna try the Yeo2017 with 200 RoIs. If it doesn't work, I'll try with 100 RoIs and it should be fine.

Thank you again for you help :)

**Comment by faskowit** [comment]
Ahhh that is an interesting idea -- the ability to provide a reference file.  I'll look into it as a possible option.  Another of the changes I am looking into is outputting better metadata from the maTT app... so maybe this could be related.

**Comment by Vince-LD** [comment]
I did not completely understand what is exactly the output of matt because it is supposed to output the subcortical regions in a different way than the "normal" atlas parcellation (???) However, even on brainlife it doesn't really seem to be the case. Maybe you could just add an argument to take the `chosen-atlas_rmap.nii.gz_remap.txt` and read it as it is already formatted and shouldn't have any index gaps. 

EDIT: the yeo17 with 200 RoIs worked!

**Comment by faskowit** [comment]
I've implemented a simple masking step, that should help to avoid the errors about the missing regions (I think). If you are using this app through brainlife, you'll need to use updated app with the new branch.   I didn't implement the additional input reference file, as it might require a bit of overhead on the BL app that I don't want to deal with.  Let's see how this works for now

**Comment by Vince-LD** [comment]
Thank you awesome! I'm gonna try it and come back to give you my feedback.
Does your new code take into acount that regions could also be missing from the parcellation?

**Comment by Vince-LD** [comment]
So after my first try, it seems to have worked very well and I get the csv with the 346 regions so that's great!
The only thing is that because the region 103 is absent from my parcellation, It is also missing in the final connmat. Nothing that I cannot fix myself and I may add a little bit of code to check for gaps in the final matrix/indexes. Thank you for your quick fix.

**Comment by faskowit** [comment]
excellent!  the change I just pushed just now to should leave a row of 0's for the empty region, when creating timeseries (but not the cm, correlation matrix).
