### ISSUE TITLE
How do I choose the fmri and mask files?

### ISSUE THREAD

**Issue by WangYunHong98** [faskowit/app-fmri-2-mat#22]
Hi @faskowit 

I used your amazing tool. It's convenient!

I have a question, should the inputs from fmriprep for ```fmri``` and ```mask``` be as shown below?

![image](https://github.com/faskowit/app-fmri-2-mat/assets/104638954/19863a6e-cec9-42bf-ad55-3bd4a2a77d4d)

Best,
Yunhong

**Comment by faskowit** [comment]
Yes those are the files!

**Comment by WangYunHong98** [comment]
Thank you @faskowit
